# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebfd88e8847326ee5c066465a9e4993d5826af59c0a7b95aa00b928a7496ff641d135998c6546c14de1092dfc64ec8f90c84aaa0bd80145818d535b296d0d7a2

test:
  secret_key_base: 80f99012958f3bf7159047b4bf25986ee91a4c7c1ece602cb219fab52f04c925b06a34530436dc6a83668ca67145a95bf96bd474fe6591186c0b7a4fe074283b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
